import type { Template, CanvasElement } from '../types';

export const DEFAULT_HACKATHON_ELEMENTS: CanvasElement[] = [
  {
    id: 'top-tag',
    label: 'Top Badge',
    type: 'text',
    x: 50,
    y: 20,
    dataSource: 'custom',
    staticValue: 'ANNUAL INNOVATION HACKATHON',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
    textCase: 'uppercase',
    color: '#38bdf8',
    visible: true,
  },
  {
    id: 'header',
    label: 'Certificate Header',
    type: 'text',
    x: 50,
    y: 28,
    dataSource: 'header',
    staticValue: 'CERTIFICATE OF PARTICIPATION',
    fontFamily: 'Cinzel',
    fontWeight: '800',
    fontSize: 48,
    textAlign: 'center',
    textCase: 'uppercase',
    color: '#ffffff',
    visible: true,
  },
  {
    id: 'subtitle',
    label: 'Subtitle',
    type: 'text',
    x: 50,
    y: 38,
    dataSource: 'subtitle',
    staticValue: 'THIS CERTIFICATE IS PROUDLY CONFERRED TO',
    fontFamily: 'Inter',
    fontWeight: '500',
    fontSize: 18,
    textAlign: 'center',
    textCase: 'uppercase',
    color: '#94a3b8',
    visible: true,
  },
  {
    id: 'name',
    label: 'Participant Name',
    type: 'text',
    x: 50,
    y: 46,
    dataSource: 'name',
    fontFamily: 'Cinzel',
    fontWeight: '700',
    fontSize: 62,
    textAlign: 'center',
    textCase: 'uppercase',
    color: '#f8bf24',
    visible: true,
  },
  {
    id: 'college',
    label: 'College / Institution',
    type: 'text',
    x: 50,
    y: 56,
    dataSource: 'college',
    fontFamily: 'Inter',
    fontWeight: '500',
    fontSize: 24,
    textAlign: 'center',
    textCase: 'none',
    color: '#93c5fd',
    visible: true,
  },
  {
    id: 'description',
    label: 'Event Description',
    type: 'text',
    x: 50,
    y: 64,
    dataSource: 'description',
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: 18,
    textAlign: 'center',
    textCase: 'none',
    color: '#e2e8f0',
    visible: true,
  },
  {
    id: 'eventTitle',
    label: 'Event Title',
    type: 'text',
    x: 50,
    y: 72,
    dataSource: 'eventTitle',
    fontFamily: 'Inter',
    fontWeight: '700',
    fontSize: 22,
    textAlign: 'center',
    textCase: 'none',
    color: '#f8bf24',
    visible: true,
  },
  {
    id: 'date',
    label: 'Issue Date',
    type: 'text',
    x: 23,
    y: 81,
    dataSource: 'date',
    fontFamily: 'Inter',
    fontWeight: '500',
    fontSize: 17,
    textAlign: 'center',
    textCase: 'none',
    color: '#94a3b8',
    visible: true,
  },
  {
    id: 'certificateId',
    label: 'Certificate ID',
    type: 'text',
    x: 77,
    y: 81,
    dataSource: 'certificateId',
    fontFamily: 'Orbitron',
    fontWeight: '600',
    fontSize: 17,
    textAlign: 'center',
    textCase: 'none',
    color: '#94a3b8',
    visible: true,
  },
  {
    id: 'qr',
    label: 'QR Code',
    type: 'qr',
    x: 50,
    y: 81,
    dataSource: 'qr',
    fontFamily: 'Inter',
    fontWeight: '400',
    fontSize: 64, // dimensions
    textAlign: 'center',
    textCase: 'none',
    color: '#ffffff',
    visible: true,
  },
  {
    id: 'sig1',
    label: 'Chair Signature',
    type: 'signature',
    x: 23,
    y: 88,
    dataSource: 'custom',
    staticValue: 'ORGANIZING CHAIR',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
    textCase: 'uppercase',
    color: '#64748b',
    visible: true,
  },
  {
    id: 'sig2',
    label: 'Faculty Convener',
    type: 'signature',
    x: 77,
    y: 88,
    dataSource: 'custom',
    staticValue: 'FACULTY CONVENER',
    fontFamily: 'Montserrat',
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
    textCase: 'uppercase',
    color: '#64748b',
    visible: true,
  },
];

export const PRESET_TEMPLATES: Template[] = [
  {
    id: 'codesprint-hackathon',
    name: 'CodeSprint Hackathon',
    category: 'HACKATHON',
    description: 'High-energy cyber tech with glowing electric cyan accents and dark geometric borders.',
    themeColor: '#0f172a',
    accentColor: '#38bdf8',
    bgType: 'svg-preset',
    elements: JSON.parse(JSON.stringify(DEFAULT_HACKATHON_ELEMENTS)),
  },
  {
    id: 'athletic-sports',
    name: 'Athletic Sports Trophy',
    category: 'SPORTS',
    description: 'Dynamic crimson & rich gold laurels with collegiate athletic borders and championship badge.',
    themeColor: '#450a0a',
    accentColor: '#eab308',
    bgType: 'svg-preset',
    elements: DEFAULT_HACKATHON_ELEMENTS.map((el) => {
      if (el.id === 'top-tag') return { ...el, staticValue: 'NATIONAL ATHLETIC CHAMPIONSHIPS', color: '#fbbf24' };
      if (el.id === 'header') return { ...el, staticValue: 'CERTIFICATE OF EXCELLENCE', color: '#ffffff' };
      if (el.id === 'name') return { ...el, color: '#f59e0b', fontFamily: 'Montserrat' };
      if (el.id === 'college') return { ...el, color: '#fef08a' };
      if (el.id === 'eventTitle') return { ...el, color: '#f59e0b' };
      return el;
    }),
  },
  {
    id: 'tech-workshop',
    name: 'Tech Workshop & Summit',
    category: 'WORKSHOP',
    description: 'Clean, high-end executive slate & emerald with subtle modern guilloche lines and minimalist badge.',
    themeColor: '#022c22',
    accentColor: '#34d399',
    bgType: 'svg-preset',
    elements: DEFAULT_HACKATHON_ELEMENTS.map((el) => {
      if (el.id === 'top-tag') return { ...el, staticValue: 'ANNUAL TECH INNOVATION SUMMIT', color: '#34d399' };
      if (el.id === 'header') return { ...el, staticValue: 'CERTIFICATE OF COMPLETION', color: '#ffffff' };
      if (el.id === 'name') return { ...el, color: '#6ee7b7', fontFamily: 'Cinzel' };
      if (el.id === 'college') return { ...el, color: '#a7f3d0' };
      if (el.id === 'eventTitle') return { ...el, color: '#34d399' };
      return el;
    }),
  },
  {
    id: 'collegiate-honor',
    name: 'Collegiate Honor & Academic',
    category: 'ACADEMIC',
    description: 'Timeless vintage ivory & ornate baroque gold filigree diploma with antique university crest.',
    themeColor: '#1e1b18',
    accentColor: '#d97706',
    bgType: 'svg-preset',
    elements: DEFAULT_HACKATHON_ELEMENTS.map((el) => {
      if (el.id === 'top-tag') return { ...el, staticValue: 'HONOR SOCIETY OF EXCELLENCE', color: '#d97706' };
      if (el.id === 'header') return { ...el, staticValue: 'CERTIFICATE OF ACADEMIC MERIT', color: '#ffffff', fontFamily: 'Playfair Display' };
      if (el.id === 'name') return { ...el, color: '#fbbf24', fontFamily: 'Playfair Display' };
      if (el.id === 'college') return { ...el, color: '#fde68a', fontFamily: 'Playfair Display' };
      if (el.id === 'eventTitle') return { ...el, color: '#fbbf24' };
      return el;
    }),
  },
];
